//! WASM Component Model host-side bindings
//!
//! Auto-generated by `wasmtime::component::bindgen!` from WIT files.
//! Generates the `PluginWorld` struct for typed invocations of plugin exported functions.

#[cfg(feature = "plugin-wasm")]
wasmtime::component::bindgen!({
    path: "plugin-wit/plugin.wit",
    world: "plugin-world",
});
