name: publish-crates

on:
  workflow_call:
    inputs:
      plan:
        description: "dist plan manifest"
        required: true
        type: string

jobs:
  publish-crates:
    runs-on: "ubuntu-22.04"
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          submodules: recursive
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - name: cargo publish axe-derive
        run: cargo publish --no-verify --allow-dirty -p axe-derive || echo "already published"
      - name: cargo publish axe
        run: cargo publish --no-verify --allow-dirty -p axe || echo "already published"
